### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mrtracy** [mrtracy/cycles_bevy_jam#19]
Core Gameplay Loop
- [x] Organization of game into Waves
- [ ] Wave generation and management
  - [x] Next wave based on previous wave
  - [ ] Additional elements into wave
- [ ] Money
- [ ] Game Over calculation

Additional Gameplay Elements
- [ ] Tile nutrient information
- [ ] Nutrient-based Growth
- [ ] Flower portion of Fruit Cycle
- [ ] Pollinator
- [ ] Tower Placement limits
- [ ] Tree Growth (more Branches)
- [ ] Root stock propagation
- [ ] Research lab

User Interface
- [x] Move UI to lower bar
- [x] Building placement buttons
- [ ] Inspector UI with Actions

Animations and Visuals
- [ ] Tree Movement animations
- [x] Show Tower Range
- [ ] Harvest Fruit Animations
- [ ] Fruit Growth Stage
- [ ] Daylight wave
